# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", type: "dhcp"
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--paravirtprovider", "kvm"]
    v.linked_clone = true if Vagrant::VERSION =~ /^1.8/
  end
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "tests/test.yml"
    ansible.sudo = true
    ansible.extra_vars = {
    }
  end
end
