---

- name: Check nginx default conf
  stat: path=/etc/nginx/conf.d/default.conf
  register: nginx_default_conf

- name: Check nginx default ssl conf
  stat: path=/etc/nginx/conf.d/example_ssl.conf
  register: nginx_default_ssl_conf

- name: Remove nginx default conf
  file: path=/etc/nginx/conf.d/default.conf state=absent
  when: nginx_default_conf.stat is defined and nginx_default_conf.stat.exists
  notify: restart nginx

- name: Remove nginx default ssl conf
  file: path=/etc/nginx/conf.d/example_ssl.conf state=absent
  when: nginx_default_ssl_conf.stat is defined and nginx_default_ssl_conf.stat.exists
  notify: restart nginx